export const TestPointFilterScreens = Object.freeze({
    LIST: "LIST",
    STATUS_FILTER: "STATUS",
    TEST_POINT_TYPE_FILTER: 'TEST_POINT_TYPE_FILTER',
    READING_FILTER: 'READING_FILTER',
    PIPELINE_FILTER: 'PIPELINE_FILTER'
})