export default {
    close: 'Close',
    create: 'Create',
    sorting: 'Sorting',
    refresh: 'Refresh',
    readings: 'Readings',
    filters: 'Filters',
    status: 'Status',
    testPointType: 'Test point type',
    markerType: 'Marker type',
    pipelines: 'Pipelines',
    hideEmptyTestPoints: 'Hide test points without readings',
    clearFilters: 'Clear filters',
    apply: 'Apply',
    qrNfcLabels: 'QR code and NFC labels',
    corrosionCalculator: 'Corrosion calculator',
    exportedFiles: 'Exported files',
    multimeter: 'Multimeter',
    neverSaved: 'Never saved',
    lastSynced: 'Last synced',
    uploadingAssets: 'Uploading assets',
    savingSurvey: 'Saving survey',
    connected: 'Connected',
    disconnected: 'Disconnected',
    upgradePremium: 'Upgrade to premium',
    exportSurvey: 'Export survey',
    saveChanges: 'Save changes',
    saving: 'Saving...',
    saveChangesAndExit: 'Save changes and exit',
    settings: 'Settings',
    importSpreadsheet: 'Import from spreadsheet',
    takePhoto: 'Take a photo',
    selectGallery: 'Select from the gallery',
    selectStorage: 'Select from storage',
    labelHint: 'The data will be saved to the label and can be accessed offline by anyone with Corpad app.',
    generateQr: 'Generate QR code',
    writeNfc: 'Write to NFC tag'
}
