export default {
    surveyName: 'Survey name',
    newSurvey: 'New survey',
    deviceBased: 'Device-based',
    deviceBasedDescription: "Survey is stored on your device inside the app folder. Doesn't require internet.",
    cloudBased: 'Cloud-based',
    cloudBasedDescription: 'Survey is stored on your device and synced with cloud storage. Requires internet and a Google account.',
    signInRequired: '(Sign in required)',
    moreOptions: 'More options ...',
    lessOptions: 'Less options ...',
    chooseTemplate: 'Choose template',
    blank: 'Blank',
    blankDescription: 'Create an empty survey with default items',
    existingSurvey: 'Based on existing survey',
    existingSurveyDescription: 'Create a copy of an existing survey without readings',
    selectSurvey: 'Select survey',
    noLocalSurveys: 'No local surveys found',
    loadingSurveyList: 'Loading survey list...',
    baseSurvey: 'Base survey',
    includeImages: 'Include images from existing survey',
    create: 'Create',
    next: 'Next',
    creatingSurvey: 'Creating survey',
    nameLabel: 'Name: {{name}}'
}
