export default {
    addPhoto: 'Add a photo',
    addReading: 'Add reading',
    save: 'Save',
    delete: 'Delete',
    coordinateCapture: 'Coordinate capture',
    accuracy: 'Accuracy:',
    capture: 'Capture',
    ratio: 'Ratio',
    factor: 'Factor',
    shuntRatio: 'Shunt ratio',
    voltageDrop: 'Voltage drop',
    target: 'Target',
    noCalculation: 'Unable to calculate',
    sideA: 'Side A',
    sideB: 'Side B',
    change: 'Change',
    currentTravels: 'Current travels {{direction}}.',
    fromSideAToSideB: 'from side A to side B',
    fromSideBToSideA: 'from side B to side A',
    layer: 'Layer #{{number}}',
    addLayer: 'Add layer ({{count}}/6)',
    maxLayers: 'Max number of layers reached',
    anode: 'Anode',
    outputCurrent: 'Anode output current',
    addAnode: 'Add anode ({{count}}/10)',
    maxAnodes: 'Max number of anodes reached',
    applyToAll: 'Apply to all',
    apply: 'Apply',
    density: 'Density',
    disconnected: 'Disconnected',
    type: 'Type',
    shorted: 'Shorted',
    material: 'Material',
    groundbedType: 'Groundbed type',
    enclosure: 'Enclosure',
    referenceCellType: 'Reference cell type',
    pipeline: 'Pipeline',
    diameter: 'Diameter',
    connectedTo: 'Connected to',
    couponType: 'Coupon type',
    anodeMaterial: 'Anode material',
    coating: 'Coating',
    bare: 'Bare',
    coated: 'Coated',
    spacingUnit: 'Spacing unit',
    resistivityUnit: 'Resistivity unit',
    comments: 'Comments',
    selectMaterial: 'Select material',
    selectResistivityUnit: 'Select resistivity unit',
    latitude: 'Latitude:',
    longitude: 'Longitude:',
    cancel: 'Cancel',
    currentControl: 'Current control',
    selectControlMode: 'Select control mode',
    currentCalculation: 'Current calculation',
    imagesCount: 'Images ({{count}}/6)'
}
