export default {
    file: {
        selectFile: 'Select file',
        next: 'Next',
        supportedFormats: 'Supported formats (.xlsx, .csv)',
        learnFormatting: 'Learn about file formatting',
        rows: 'Rows: {{count}}',
        columns: 'Columns: {{count}}',
        rowsColumns: 'Rows: {{rows}}, Columns: {{columns}}',
        selectItem: 'SELECT IMPORTING SURVEY ITEM',
        preparationTitle: 'How to prepare your files',
        preparation: {
            spreadsheet: '1. Preparing your spreadsheet for import',
            formatting: '2. Formatting data in cells',
            tips: '3. Useful tips',
            ensureSize: 'Ensure the spreadsheet file size is less than',
            eachRow: 'Each row should represent a separate item.',
            firstRow: 'The first row must contain',
            headers: 'headers',
            describeColumns: 'that describe the data in each column.',
            avoid: 'Avoid using',
            mergedCells: 'merged cells, blank rows,',
            blankColumns: 'or blank columns.',
            onlyFirst: 'If your file contains multiple worksheets,',
            firstSheet: 'only the first sheet',
            imported: 'will be imported.',
            specialCharacters: 'Do not use',
            specialCharacterLabel: 'special characters',
            nameProperty: 'in columns intended for the',
            namePropertyLabel: '"Name" property',
            removed: 'These characters will be removed during import.',
            numerical: 'Numerical values',
            noText: 'should not include text in the same cell (e.g.,',
            splitValue: 'should be split into',
            oneColumn: 'in one column and',
            anotherColumn: 'in another, if applicable).',
            variousUnits: 'You can import values with',
            units: 'various units',
            cancelRecent: 'You can cancel recent imports immediately after they are performed. This option is available on the',
            importScreen: 'Import',
            screen: 'screen.'
        }
    },
    parameters: {
        fixedValue: 'Use fixed value for each imported item',
        fixedValueShort: 'Use fixed value for each item',
        valuesFromColumn: 'Use values from a column in data file',
        selectDataColumn: 'Select data column',
        selectDataColumns: 'Select data columns',
        unit: 'Unit',
        unitHint: 'Unit must match the one used in spreadsheet',
        defaultName: 'Use default name values',
        startIndex: 'Start with index',
        mergeColumns: 'Merge values from two or more columns in data file',
        mappedAttributes: 'Mapped attributes',
        noMappedAttributes: 'No mapped attributes.',
        propertyValue: 'Property value',
        valuesFromSpreadsheet: 'Values from spreadsheet',
        selectValues: 'Select values',
        howToMap: 'How to map attributes?',
        mappingStepOne: '1. Select data column you wish to use for this property.',
        mappingStepTwo: '2. Select property value.',
        mappingStepThree: '3. Select one or more values from spreadsheet file. When importing, these values will be converted to corresponding property value.',
        selectColumnToStart: 'Select a data column to start mapping',
        allColumnValuesMapped: 'All values from data column were mapped',
        allPropertyValuesMapped: 'All property values were mapped',
        allValuesMapped: 'All values were mapped',
        save: 'Save',
        error: 'Error',
        empty: '<Empty>'
    },
    item: {
        import: 'Import',
        back: 'Back',
        importFromSpreadsheet: 'Import from spreadsheet',
        toCreate: '{{name}} to create: {{count}}',
        cancel: 'Cancel',
        start: 'Start',
        importing: 'Importing',
        completed: 'Import completed',
        failed: 'Import failed',
        created: 'Created {{name}}: {{count}}',
        warnings: 'Warnings: {{count}}',
        errors: 'Errors: {{count}}',
        close: 'Close',
        item: 'Item',
        moreValues: '& {{count}} more',
        goToList: 'Go to list',
        details: 'Details',
        importSettings: 'Import settings',
        field: 'field:',
        fixedValueBadge: 'Fixed value',
        defaultNameBadge: 'Default name',
        unableToImport: 'Unable to import item from provided data',
        row: 'Row {{count}}',
        error: 'Error',
        dataFile: 'Data file',
        rowsColumns: 'Rows: {{rows}}, Columns: {{columns}}',
        noItemsToImport: 'No items to import. Data file is empty',
        importedSuccessfully: 'All items were imported successfully.',
        imported: 'Imported {{name}}: {{count}}',
        deleting: 'Deleting {{name}}: {{count}}',
        undoImport: 'Undo import',
        undo: 'Undo',
        lastStatus: 'Last import status',
        importedRows: 'Imported rows with issues',
        currentDirection: 'Current travels from side {{direction}}',
        change: 'Change',
        sideA: 'Side A',
        sideB: 'Side B',
        selectItems: 'Select items',
        pipeline: 'Pipeline',
        selectPipeline: 'Select pipeline',
        connectedTo: 'Connected to',
        disconnected: 'Disconnected',
        currentControlMode: 'Current control mode',
        coarseFine: 'Coarse - Fine',
        valueVa: 'Value (VA %)',
        currentDensityHint: 'Current density will be calculated after importing',
        shuntCurrentHint: 'Shunt current will be calculated after importing',
        isolationCurrentHint: 'Shorting current value for an isolation reading will not be imported, if imported shorted property for this reading equals "No".',
        sideDirection: {
            aToB: 'A to side B.',
            bToA: 'B to side A.'
        }
    },
    warnings: {
        testPointType: 'Test point type was not defined. Default test point type is set.',
        cannotCreate: '"{{label}}" cannot be created from provided data.',
        nameConverted: 'Name property {{originalValue}} was converted to {{convertedValue}}',
        status: 'Status is not defined. Default status was set.',
        valueTooLong: 'Value of property " {{property}} " is too long and was cropped to a maximum allowed length.',
        invalidValues: 'Some values may be invalid and were converted to null'
    }
}
