export default {
    testPoints: 'Test points: {{count}}',
    noItems: 'No items',
    maxVoltage: 'Max. voltage',
    maxCurrent: 'Max. current',
    model: 'Model',
    serialNumber: 'Serial number',
    powerSource: 'Power source',
    currentControl: 'Current control',
    pipeline: 'Pipeline',
    diameter: 'Diameter',
    connectedTo: 'Connected to',
    type: 'Type',
    area: 'Area',
    current: 'Current',
    currentDensity: 'Current density',
    comment: 'Comment',
    anodeMaterial: 'Anode material',
    bedType: 'Bed type',
    enclosureType: 'Enclosure type',
    anodeOutputCurrent: 'Anode output current',
    status: 'Status',
    shorted: 'Shorted',
    isolated: 'Isolated',
    shortingCurrent: 'Shorting current',
    isolationType: 'Isolation type',
    factor: 'Factor',
    shuntRatio: 'Shunt ratio',
    voltageDrop: 'Voltage drop',
    voltage: 'Voltage',
    target: 'Target',
    description: 'Description',
    material: 'Material',
    size: 'Size',
    coating: 'Coating',
    product: 'Product',
    error: 'Error',
    resistance: 'Resistance',
    resistivity: 'Resistivity',
    layer: 'Layer',
    layerTitle: 'Layer ({{start}} - {{end}} {{unit}})',
    anode: 'Anode',
    average: 'Average',
    layers: 'Layers',
    maxValue: 'Max. {{value}}',
    minValue: 'Min. {{value}}'
}
