export default {
    export: 'Export',
    deleteAll: 'Delete all',
    history: 'History',
    noSavedReadings: 'No saved readings',
    ranges: 'Ranges',
    measurementModes: 'Measurement modes',
    error: 'Error',
    max: 'Max.',
    resume: 'Resume',
    hold: 'Hold',
    save: 'Save',
    digits: 'Digits',
    graph: 'Graph',
    yAxisLimit: 'Y-axis limit',
    xAxisLimit: 'X-axis limit',
    readingSaved: 'Reading saved',
    exporting: 'Exporting',
    noMultimeterFound: 'No multimeter found',
    notConnected: 'Multimeter is not connected',
    screenUnavailable: 'Screen is not available',
    historyReadings: 'History readings',
    delete: 'Delete',
    cancel: 'Cancel',
    back: 'Back'
}
