export default {
    connectDevice: 'Connect device',
    connectHint: 'Make sure that multimeter is ready to connect and press "Continue."',
    continue: 'Continue',
    cancel: 'Cancel',
    pairedDevice: 'Paired device',
    connecting: 'Connecting',
    connect: 'Connect',
    connectDescription: 'Make sure multimeter is ready to connect',
    measurements: 'Measurements',
    settings: 'Settings',
    settingsDescription: 'Adjust ON/OFF time cycles, capture rate and mode',
    unpair: 'Unpair',
    multimeter: 'Multimeter',
    multimeterDescription: 'Connect digital bluetooth multimeter in order to capture readings.',
    findSupported: 'Find supported multimeters at',
    connected: 'Connected',
    disconnected: 'Disconnected',
    timeSynchronization: 'Time synchronization',
    syncing: 'Syncing',
    synced: 'Synced via {{source}} | Delta {{delta}} ms',
    notSynced: 'Not synced',
    upgradePremium: 'Upgrade to premium',
    pairing: 'Pairing',
    search: 'Search for multimeters',
    searching: 'Searching for multimeters',
    bluetoothOff: 'Bluetooth is off',
    connectedOtherApp: 'Connected with another app (unavailable)',
    availableDevices: 'Available devices',
    captureRate: 'Capture rate',
    hzUs: '60 Hz (US, Canada)',
    hzOther: '50 Hz (Other)',
    detectOnOff: 'Detect ON/OFF cycle',
    interruptionCycle: 'Interruption cycle duration (ON | OFF)',
    on: 'On',
    off: 'Off',
    timeSynchronizationMethod: 'Time synchronization method',
    gps: 'GPS',
    ntp: 'NTP (over Internet)',
    mixed: 'Mixed',
    firstCycle: 'First cycle',
    onDelay: 'On delay',
    offDelay: 'Off delay',
    errors: 'Errors',
    cycleTimeError: '- Cycle time must be less than 60 000 ms and more than 200 ms.',
    delayError: '- Delay must be less than half of cycle time and more than 20 ms.',
    cycleDetectionMethod: 'Cycle detection method',
    gpsDescription: 'Reporst captured values at the begining of ON and OFF cycles. Uses GPS or NTP to syncronize with global time. Cycle must start at the begining of a minute.',
    highLowDescription: 'Captures highest and lowest values within a cycle. Updates once per cycle.',
    cycledDescription: 'Evaluates values and determines shift between cycles. Reports captured values at the begining of ON and OFF cycles. Only works for cycles with different ON/OFF durations.',
    save: 'Save',
    back: 'Back'
}
