export default {
    survey: 'Survey',
    app: 'App',
    other: 'Other',
    surveyOverview: 'Survey overview',
    referenceCells: 'Reference cells',
    potentials: 'Potentials',
    exportSurvey: 'Export survey',
    about: 'About',
    language: 'Language',
    languageDescription: 'Select the language used by the app',
    digitalMultimeter: 'Digital multimeter',
    externalLinks: 'QR code and NFC labels',
    calculator: 'Corrosion calculator',
    defaultNames: 'Default names',
    defaultNamesDescription: 'Manage default names for new test points, rectifiers, readings and etc.',
    exportedFiles: 'Exported files',
    exitWithoutSaving: 'Exit without saving',
    surveyOverviewDescription: 'See general stats of your survey, and status of completion',
    referenceCellsDescription: 'Add and remove portable reference cells',
    potentialsDescription: 'Control default units for potential readings, add and remove potential reading types',
    imagesDescription: 'View all the images assigned to test points and rectifiers in this survey',
    exportSurveyDescription: 'Export data from survey to a spreadsheet file and save it to your device',
    aboutDescription: 'Check app version, legal information and support contact',
    multimeterDescription: 'Control bluetooth multimeter settings',
    externalLinksAndroidDescription: 'View recently scanned labels',
    externalLinksDescription: 'Launch NFC scanning and view recently scanned labels',
    calculatorDescription: 'Execute number of cathodic protection calculations and export results as files',
    exportedFilesDescription: 'View exported survey files, delete or share them with different apps',
    exitDescription: 'Exit to the main screen. All changes made after last sync will not be saved in file. Use with caution.',
    privacyPolicy: 'Privacy policy',
    terms: 'Terms and conditions',
    licenses: 'Licenses',
    documentation: 'Documentation',
    support: 'Support',
    createdBy: 'Created by',
    followOnX: 'Follow on X',
    appVersion: 'Corpad for {{platform}}.\nVersion {{version}}',
    subscription: 'Subscription',
    manage: 'Manage',
    expiresOn: '(Expires on {{date}})',
    check: 'Check',
    upgrade: 'Upgrade',
    noLabels: 'No labels found.',
    readNfc: 'Read NFC label',
    recentlyScanned: 'Recently scanned labels',
    scannedOn: 'Scanned on {{date}}',
    noImages: 'No images found.',
    loading: 'Loading...',
    added: 'Added',
    surveyName: 'Survey name',
    numberOfImages: 'Number of images',
    sizeOnDisk: 'Size on disk',
    save: 'Save',
    category: 'Category',
    defaultNamePrefix: 'Default name prefix',
    defaultNamesHint: 'Default names are used when creating new survey item (e.g. test point, rectifier or pipeline) or new reading. You can manually declare names in edit screen, or you can customize default names here, and they will be used automatically.',
    usePipelineName: 'Use pipeline name as default name for pipeline test leads and risers',
    example: 'Example',
    error: 'Error',
    portableReferenceCells: 'Portable reference cells',
    referenceCellsHint: 'You can have more than one portable reference cell in a survey. Potential readings assigned to the active reference cell will be displayed in the main list. Automatically created potentials are assigned to active reference cell.',
    name: 'Name',
    selectType: 'Select type',
    referenceCellType: 'Reference cell type',
    addReferenceCell: 'Add reference cell',
    standardPotentialTypes: 'Standard potential types',
    customPotentialTypes: 'Custom potential types',
    addPotentialType: 'Add potential type',
    autoCreatePotentials: 'Auto-create potentials',
    autoCreateDescription: 'New readings will have ON/OFF potential fields added upon creation',
    newPotentialType: 'New potential type',
    potentialType: 'Potential type',
    create: 'Create',
    mainReference: 'Main reference',
    unknownType: 'Unknown type',
    lastUpdated: 'Last updated',
    surveyArea: 'Survey area',
    radius: 'Radius',
    totalReadings: 'Total number of readings',
    images: 'Images',
    imageAssets: 'Number of image assets',
    newSurvey: 'My survey',
    testPoints: 'Test points',
    rectifiers: 'Rectifiers',
    itemProperties: 'ITEM PROPERTIES',
    exportedItems: 'EXPORTED ITEMS',
    format: 'FORMAT',
    mapLayers: 'MAP LAYERS',
    includeMapLayers: 'Include map layers',
    includeImages: 'Include images',
    yes: 'Yes',
    no: 'No',
    sorting: 'Sorting',
    properties: 'Properties:',
    potentialsTitle: 'POTENTIALS',
    referenceCell: 'Reference cell:',
    potentialTypes: 'Potential types:',
    readingTypes: 'Reading types:',
    groupedBy: 'Grouped by:',
    pipelines: 'Pipelines:',
    otherTitle: 'OTHER',
    exportProperties: 'Properties: ',
    export: 'Export',
    next: 'Next',
    referenceCellTitle: 'REFERENCE CELL',
    potentialTypesTitle: 'POTENTIAL TYPES',
    readingTypesTitle: 'READING TYPES',
    potentialGroupingTitle: 'POTENTIALS GROUPING',
    exportPotentials: 'Export potentials',
    groupReadingType: 'Group by reading type',
    groupPipeline: 'Group by pipeline',
    unassigned: 'Unassigned',
    preview: 'Preview',
    share: 'Share',
    openIn: 'Open in...',
    saveToDownloads: 'Save to Downloads',
    delete: 'Delete',
    noFiles: 'No files found',
    noFilesDescription: 'You can manage .csv, .kml and .zip files here, after exporting data from surveys.',
    saved: 'Saved',
    savedToDownloads: 'Saved to Downloads',
    deleted: '{{name}} was deleted',
    allFilesDeleted: 'All files were deleted',
    deleteAll: 'Delete all',
    exitingSurvey: 'Exiting survey',
    exit: 'Exit',
    cancel: 'Cancel',
    exporting: 'Exporting',
    creatingFile: 'Creating new .{{type}} file',
    includeImagesExport: 'Export images',
    thirdPartyNotices: 'Third Party Notices',
    licenseDescription: 'The following components are licensed under the {{title}} licence reproduced below:',
    licenseListDescription: 'The following list third party software that may be contained in portion of this app:',
    pipeline: 'Pipeline',
    readingType: 'Reading type'
}
