export default {
    today: 'Today',
    earlier: 'Earlier',
    downloadingAssets: 'Downloading assets',
    uploadingAssets: 'Uploading assets',
    loadingSurvey: 'Loading survey',
    deletingSurvey: 'Deleting survey',
    exportingSurvey: 'Exporting survey',
    copyingToDevice: 'Copying survey to device',
    copyingToCloud: 'Copying survey to cloud',
    savingToDownloads: 'Saving survey to downloads',
    savedToDownloads: 'Saved to Downloads',
    saveToDownloads: 'Save to Downloads',
    copyToDevice: 'Copy to device',
    copyToCloud: 'Copy to cloud',
    shareFile: 'Share file',
    delete: 'Delete',
    cancel: 'Cancel',
    signedAs: 'Signed as',
    logOut: 'Log out',
    noSurveyFiles: 'No survey files found',
    oops: 'Oops!',
    noInternet: 'There is no internet connection. Please check your connection.',
    createOrOpenSurvey: 'Create or open a survey file by tapping the folder and selecting from your device or cloud storage.',
    newToCorpad: 'New to Corpad? Check our documentation at',
    createNewSurvey: 'Create new survey',
    importSurvey: 'Import survey from spreadsheet',
    or: 'or'
}
