export default {
    calculatorOptions: 'Calculator options',
    displayCalculatorMarkers: 'Display calculator markers',
    displayedMapLayers: 'Displayed map layers',
    addMapLayer: 'Add a map layer',
    supportedFormats: 'Supported formats: .kml, .kmz, .gpx, .geojson',
    maxLimitReached: 'Max. limit reached',
    upgradePremium: 'Upgrade to premium',
    features: 'Features: {{count}}',
    emptyDescription: 'Import markers, polylines and polygons into the survey from geodata file.',
    goTo: 'Go to',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    cancel: 'Cancel',
    applyingSettings: 'Applying new settings',
    layerName: 'Layer name',
    color: 'Color',
    strokeWidth: 'Stroke width',
    comments: 'Comments',
    typeComments: 'Type your comments here',
    importingFile: 'Importing file',
    selectFile: 'Select file',
    fileSizeLimit: 'File size limit: 1 MB',
    newLayer: 'New layer',
    saving: 'Saving',
    create: 'Create',
    save: 'Save'
}
