export default {
    back: 'Back',
    testPoints: 'Test points: {{count}}',
    noItems: 'No items',
    error: 'Error',
    resistance: 'Resistance',
    resistivity: 'Resistivity',
    share: 'Share',
    save: 'Save',
    addingImage: 'Adding image',
    savedToDownloads: 'Saved to Downloads',
    deletingPhoto: 'Deleting photo',
    showOnMap: 'Show on map',
    addPhoto: 'Add a photo',
    addReading: 'Add reading',
    imagesCount: 'Images ({{count}}/6)',
    edit: 'Edit',
    createLabel: 'Create label',
    delete: 'Delete',
    cancel: 'Cancel',
    show: 'Show',
    hide: 'Hide',
    controls: 'controls',
    currentMeasurement: 'Current measurement',
    direct: 'Direct',
    shunt: 'Shunt',
    material: 'Material',
    anodeMaterial: 'Anode material',
    anode: 'Anode',
    bedType: 'Bed type',
    enclosureType: 'Enclosure type',
    anodeOutputCurrent: 'Anode output current',
    connectedTo: 'Connected to',
    disconnected: 'Disconnected',
    type: 'Type',
    area: 'Area',
    density: 'Density',
    current: 'Current',
    voltage: 'Voltage',
    target: 'Target',
    maxValue: 'Max. {{value}}',
    minValue: 'Min. {{value}}',
    shuntRatio: 'Shunt ratio',
    factor: 'Factor',
    voltageDrop: 'Voltage drop',
    isolationType: 'Isolation type',
    shorted: 'Shorted',
    diameter: 'Diameter',
    pipeline: 'Pipeline',
    comment: 'Comment',
    description: 'Description',
    status: 'Status',
    isolated: 'Isolated',
    maxVoltage: 'Max. voltage',
    maxCurrent: 'Max. current',
    model: 'Model',
    serialNumber: 'Serial number',
    powerSource: 'Power source',
    currentControl: 'Current control',
    size: 'Size',
    coating: 'Coating',
    product: 'Product',
    average: 'Average',
    layers: 'Layers',
    layer: 'Layer ({{start}} - {{end}} {{unit}})',
    bytes: 'bytes',
    nfc: {
        preparing: 'Creating link...',
        ready: 'Ready to write',
        writing: 'Writing...',
        success: 'Completed!',
        error: 'Error!',
        holdPhone: 'Hold your phone near the NFC label to record item data.',
        written: 'Item information was written on the NFC label.',
        notFormatted: 'NFC label is not formatted. Read more at',
        readOnly: 'NFC label is locked to read-only mode.',
        notEnoughSpace: 'There is not enough space on the NFC tag. Read more at',
        turnedOff: 'NFC is turned off. Please enable NFC in settings.',
        notSupported: 'NFC is not supported for this device.',
        linkTooLong: 'Excessive information recorded on the NFC label.',
        cancel: 'Cancel',
        close: 'Close',
        retry: 'Retry'
    }
}
