import englishBottomSheet from '../en/bottomSheet'

export default {
    ...englishBottomSheet,
    close: 'Cerrar',
    create: 'Crear',
    sorting: 'Orden',
    refresh: 'Actualizar',
    readings: 'Lecturas',
    filters: 'Filtros',
    status: 'Estado',
    testPointType: 'Tipo de punto de prueba',
    markerType: 'Tipo de marcador',
    pipelines: 'Líneas',
    hideEmptyTestPoints: 'Ocultar puntos de prueba sin lecturas',
    clearFilters: 'Borrar filtros',
    apply: 'Aplicar',
    qrNfcLabels: 'Etiquetas QR y NFC',
    corrosionCalculator: 'Calculadora de corrosión',
    exportedFiles: 'Archivos exportados',
    multimeter: 'Multímetro',
    neverSaved: 'Nunca guardado',
    lastSynced: 'Última sincronización',
    uploadingAssets: 'Subiendo recursos',
    savingSurvey: 'Guardando estudio',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    upgradePremium: 'Actualizar a premium',
    exportSurvey: 'Exportar estudio',
    saveChanges: 'Guardar cambios',
    saving: 'Guardando...',
    saveChangesAndExit: 'Guardar cambios y salir',
    settings: 'Configuración',
    importSpreadsheet: 'Importar desde una hoja de cálculo',
    takePhoto: 'Tomar una foto',
    selectGallery: 'Seleccionar de la galería',
    selectStorage: 'Seleccionar del almacenamiento',
    labelHint: 'Los datos se guardarán en la etiqueta y cualquier persona con la aplicación Corpad podrá acceder a ellos sin conexión.',
    generateQr: 'Generar código QR',
    writeNfc: 'Escribir en etiqueta NFC'
}
