import englishEdit from '../en/edit'

export default {
    ...englishEdit,
    addPhoto: 'Añadir una foto',
    addReading: 'Añadir lectura',
    save: 'Guardar',
    delete: 'Eliminar',
    coordinateCapture: 'Captura de coordenadas',
    accuracy: 'Precisión:',
    capture: 'Capturar',
    ratio: 'Relación',
    factor: 'Factor',
    shuntRatio: 'Relación del shunt',
    voltageDrop: 'Caída de tensión',
    target: 'Objetivo',
    noCalculation: 'No se puede calcular',
    sideA: 'Lado A',
    sideB: 'Lado B',
    change: 'Cambiar',
    currentTravels: 'La corriente viaja {{direction}}.',
    fromSideAToSideB: 'del lado A al lado B',
    fromSideBToSideA: 'del lado B al lado A',
    layer: 'Capa n.º {{number}}',
    addLayer: 'Añadir capa ({{count}}/6)',
    maxLayers: 'Se alcanzó el número máximo de capas',
    anode: 'Ánodo',
    outputCurrent: 'Corriente de salida del ánodo',
    addAnode: 'Añadir ánodo ({{count}}/10)',
    maxAnodes: 'Se alcanzó el número máximo de ánodos',
    applyToAll: 'Aplicar a todos',
    apply: 'Aplicar',
    density: 'Densidad',
    disconnected: 'Desconectado',
    type: 'Tipo',
    shorted: 'Cortocircuitado',
    material: 'Material',
    groundbedType: 'Tipo de lecho',
    enclosure: 'Carcasa',
    referenceCellType: 'Tipo de celda de referencia',
    pipeline: 'Línea',
    diameter: 'Diámetro',
    connectedTo: 'Conectado a',
    couponType: 'Tipo de cupón',
    anodeMaterial: 'Material del ánodo',
    coating: 'Revestimiento',
    bare: 'Sin revestimiento',
    coated: 'Revestido',
    spacingUnit: 'Unidad de separación',
    resistivityUnit: 'Unidad de resistividad',
    comments: 'Comentarios',
    selectMaterial: 'Seleccionar material',
    selectResistivityUnit: 'Seleccionar unidad de resistividad',
    latitude: 'Latitud:',
    longitude: 'Longitud:',
    cancel: 'Cancelar',
    currentControl: 'Control de corriente',
    selectControlMode: 'Seleccionar modo de control',
    currentCalculation: 'Cálculo de corriente',
    imagesCount: 'Imágenes ({{count}}/6)'
}
