import englishImport from '../en/import'

export default {
    ...englishImport,
    file: {
        ...englishImport.file,
        selectFile: 'Seleccionar archivo',
        next: 'Siguiente',
        supportedFormats: 'Formatos compatibles (.xlsx, .csv)',
        learnFormatting: 'Información sobre el formato de los archivos',
        rows: 'Filas: {{count}}',
        columns: 'Columnas: {{count}}',
        rowsColumns: 'Filas: {{rows}}, Columnas: {{columns}}',
        selectItem: 'SELECCIONE EL ELEMENTO DEL ESTUDIO QUE IMPORTAR',
        preparationTitle: 'Cómo preparar sus archivos',
        preparation: {
            ...englishImport.file.preparation,
            spreadsheet: '1. Preparar la hoja de cálculo para importar',
            formatting: '2. Dar formato a los datos de las celdas',
            tips: '3. Consejos útiles',
            ensureSize: 'Asegúrese de que el archivo de hoja de cálculo tenga un tamaño inferior a',
            eachRow: 'Cada fila debe representar un elemento independiente.',
            firstRow: 'La primera fila debe contener',
            headers: 'encabezados',
            describeColumns: 'que describan los datos de cada columna.',
            avoid: 'Evite usar',
            mergedCells: 'celdas combinadas, filas vacías',
            blankColumns: 'o columnas vacías.',
            onlyFirst: 'Si el archivo contiene varias hojas de cálculo,',
            firstSheet: 'solo se importará la primera hoja',
            imported: '.',
            specialCharacters: 'No use',
            specialCharacterLabel: 'caracteres especiales',
            nameProperty: 'en las columnas destinadas a la propiedad',
            namePropertyLabel: '"Nombre"',
            removed: 'Estos caracteres se eliminarán durante la importación.',
            numerical: 'Los valores numéricos',
            noText: 'no deben incluir texto en la misma celda (por ejemplo,',
            splitValue: 'debe dividirse en',
            oneColumn: 'en una columna y',
            anotherColumn: 'en otra, si corresponde).',
            variousUnits: 'Puede importar valores con',
            units: 'distintas unidades',
            cancelRecent: 'Puede cancelar las importaciones recientes inmediatamente después de realizarlas. Esta opción está disponible en la pantalla de',
            importScreen: 'importación',
            screen: '.'
        }
    },
    parameters: {
        ...englishImport.parameters,
        fixedValue: 'Usar un valor fijo para cada elemento importado',
        fixedValueShort: 'Usar un valor fijo para cada elemento',
        valuesFromColumn: 'Usar valores de una columna del archivo de datos',
        selectDataColumn: 'Seleccionar columna de datos',
        selectDataColumns: 'Seleccionar columnas de datos',
        unit: 'Unidad',
        unitHint: 'La unidad debe coincidir con la usada en la hoja de cálculo',
        defaultName: 'Usar valores de nombre predeterminados',
        startIndex: 'Comenzar con el índice',
        mergeColumns: 'Combinar valores de dos o más columnas del archivo de datos',
        mappedAttributes: 'Atributos asignados',
        noMappedAttributes: 'No hay atributos asignados.',
        propertyValue: 'Valor de la propiedad',
        valuesFromSpreadsheet: 'Valores de la hoja de cálculo',
        selectValues: 'Seleccionar valores',
        howToMap: '¿Cómo asignar atributos?',
        mappingStepOne: '1. Seleccione la columna de datos que desea usar para esta propiedad.',
        mappingStepTwo: '2. Seleccione el valor de la propiedad.',
        mappingStepThree: '3. Seleccione uno o más valores del archivo de hoja de cálculo. Durante la importación, estos valores se convertirán al valor de propiedad correspondiente.',
        selectColumnToStart: 'Seleccione una columna de datos para comenzar la asignación',
        allColumnValuesMapped: 'Todos los valores de la columna de datos están asignados',
        allPropertyValuesMapped: 'Todos los valores de la propiedad están asignados',
        allValuesMapped: 'Todos los valores están asignados',
        save: 'Guardar',
        error: 'Error',
        empty: '<Vacío>'
    },
    item: {
        ...englishImport.item,
        import: 'Importar',
        back: 'Atrás',
        importFromSpreadsheet: 'Importar desde una hoja de cálculo',
        toCreate: '{{name}} para crear: {{count}}',
        cancel: 'Cancelar',
        start: 'Iniciar',
        importing: 'Importando',
        completed: 'Importación completada',
        failed: 'Importación fallida',
        created: 'Creados {{name}}: {{count}}',
        warnings: 'Advertencias: {{count}}',
        errors: 'Errores: {{count}}',
        close: 'Cerrar',
        item: 'Elemento',
        moreValues: '& {{count}} más',
        goToList: 'Ir a la lista',
        details: 'Detalles',
        importSettings: 'Configuración de importación',
        field: 'campo:',
        fixedValueBadge: 'Valor fijo',
        defaultNameBadge: 'Nombre predeterminado',
        unableToImport: 'No se pudo importar el elemento con los datos proporcionados',
        row: 'Fila {{count}}',
        error: 'Error',
        dataFile: 'Archivo de datos',
        rowsColumns: 'Filas: {{rows}}, Columnas: {{columns}}',
        noItemsToImport: 'No hay elementos para importar. El archivo de datos está vacío',
        importedSuccessfully: 'Todos los elementos se importaron correctamente.',
        imported: 'Importados {{name}}: {{count}}',
        deleting: 'Eliminando {{name}}: {{count}}',
        undoImport: 'Deshacer importación',
        undo: 'Deshacer',
        lastStatus: 'Estado de la última importación',
        importedRows: 'Filas importadas con problemas',
        currentDirection: 'La corriente viaja del lado {{direction}}',
        change: 'Cambiar',
        sideA: 'Lado A',
        sideB: 'Lado B',
        selectItems: 'Seleccionar elementos',
        pipeline: 'Línea',
        selectPipeline: 'Seleccionar línea',
        connectedTo: 'Conectado a',
        disconnected: 'Desconectado',
        currentControlMode: 'Modo de control de corriente',
        coarseFine: 'Grueso - fino',
        valueVa: 'Valor (VA %)',
        currentDensityHint: 'La densidad de corriente se calculará después de importar',
        shuntCurrentHint: 'La corriente de derivación se calculará después de importar',
        isolationCurrentHint: 'El valor de corriente de cortocircuito de una lectura de aislamiento no se importará si la propiedad de cortocircuito importada para esta lectura equivale a "No".',
        sideDirection: {
            aToB: 'A al lado B.',
            bToA: 'B al lado A.'
        }
    },
    warnings: {
        ...englishImport.warnings,
        testPointType: 'No se definió el tipo de punto de prueba. Se estableció el tipo de punto de prueba predeterminado.',
        cannotCreate: 'No se puede crear "{{label}}" con los datos proporcionados.',
        nameConverted: 'La propiedad de nombre {{originalValue}} se convirtió a {{convertedValue}}',
        status: 'No se definió el estado. Se estableció el estado predeterminado.',
        valueTooLong: 'El valor de la propiedad " {{property}} " es demasiado largo y se recortó al máximo permitido.',
        invalidValues: 'Algunos valores pueden no ser válidos y se convirtieron a nulo'
    }
}
