import englishItemView from '../en/itemView'

export default {
    ...englishItemView,
    testPoints: 'Puntos de prueba: {{count}}',
    noItems: 'No hay elementos',
    maxVoltage: 'Tensión máx.',
    maxCurrent: 'Corriente máx.',
    model: 'Modelo',
    serialNumber: 'Número de serie',
    powerSource: 'Fuente de alimentación',
    currentControl: 'Control de corriente',
    pipeline: 'Línea',
    diameter: 'Diámetro',
    connectedTo: 'Conectado a',
    type: 'Tipo',
    area: 'Área',
    current: 'Corriente',
    currentDensity: 'Densidad de corriente',
    comment: 'Comentario',
    anodeMaterial: 'Material del ánodo',
    bedType: 'Tipo de lecho',
    enclosureType: 'Tipo de carcasa',
    anodeOutputCurrent: 'Corriente de salida del ánodo',
    status: 'Estado',
    shorted: 'Cortocircuitado',
    isolated: 'Aislado',
    shortingCurrent: 'Corriente de cortocircuito',
    isolationType: 'Tipo de aislamiento',
    factor: 'Factor',
    shuntRatio: 'Relación del shunt',
    voltageDrop: 'Caída de tensión',
    voltage: 'Tensión',
    target: 'Objetivo',
    description: 'Descripción',
    material: 'Material',
    size: 'Tamaño',
    coating: 'Revestimiento',
    product: 'Producto',
    error: 'Error',
    resistance: 'Resistencia',
    resistivity: 'Resistividad',
    layer: 'Capa',
    layerTitle: 'Capa ({{start}} - {{end}} {{unit}})',
    anode: 'Ánodo',
    average: 'Promedio',
    layers: 'Capas',
    maxValue: 'Máx. {{value}}',
    minValue: 'Mín. {{value}}'
}
