import englishMultimeterSettings from '../en/multimeterSettings'

export default {
    ...englishMultimeterSettings,
    connectDevice: 'Conectar dispositivo',
    connectHint: 'Asegúrese de que el multímetro esté listo para conectarse y pulse «Continuar».',
    continue: 'Continuar',
    cancel: 'Cancelar',
    pairedDevice: 'Dispositivo vinculado',
    connecting: 'Conectando',
    connect: 'Conectar',
    connectDescription: 'Asegúrese de que el multímetro esté listo para conectarse',
    measurements: 'Mediciones',
    settings: 'Configuración',
    settingsDescription: 'Ajuste los ciclos de tiempo ACTIVADO/DESACTIVADO, la frecuencia de captura y el modo',
    unpair: 'Desvincular',
    multimeter: 'Multímetro',
    multimeterDescription: 'Conecte un multímetro digital Bluetooth para capturar lecturas.',
    findSupported: 'Encuentre multímetros compatibles en',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    timeSynchronization: 'Sincronización de hora',
    syncing: 'Sincronizando',
    synced: 'Sincronizado mediante {{source}} | Diferencia {{delta}} ms',
    notSynced: 'No sincronizado',
    upgradePremium: 'Actualizar a premium',
    pairing: 'Vinculando',
    search: 'Buscar multímetros',
    searching: 'Buscando multímetros',
    bluetoothOff: 'Bluetooth está desactivado',
    connectedOtherApp: 'Conectado con otra aplicación (no disponible)',
    availableDevices: 'Dispositivos disponibles',
    captureRate: 'Frecuencia de captura',
    hzUs: '60 Hz (EE. UU., Canadá)',
    hzOther: '50 Hz (otros)',
    detectOnOff: 'Detectar ciclo ACTIVADO/DESACTIVADO',
    interruptionCycle: 'Duración del ciclo de interrupción (ACTIVADO | DESACTIVADO)',
    on: 'Activado',
    off: 'Desactivado',
    timeSynchronizationMethod: 'Método de sincronización de hora',
    gps: 'GPS',
    ntp: 'NTP (por Internet)',
    mixed: 'Mixto',
    firstCycle: 'Primer ciclo',
    onDelay: 'Retardo de activación',
    offDelay: 'Retardo de desactivación',
    errors: 'Errores',
    cycleTimeError: '- El tiempo de ciclo debe ser inferior a 60 000 ms y superior a 200 ms.',
    delayError: '- El retardo debe ser inferior a la mitad del tiempo de ciclo y superior a 20 ms.',
    cycleDetectionMethod: 'Método de detección del ciclo',
    gpsDescription: 'Informa de los valores capturados al inicio de los ciclos ACTIVADO y DESACTIVADO. Usa GPS o NTP para sincronizar con la hora global. El ciclo debe comenzar al inicio de un minuto.',
    highLowDescription: 'Captura los valores máximo y mínimo de un ciclo. Se actualiza una vez por ciclo.',
    cycledDescription: 'Evalúa los valores y determina el desplazamiento entre ciclos. Informa de los valores capturados al inicio de los ciclos ACTIVADO y DESACTIVADO. Solo funciona con ciclos de distinta duración ACTIVADO/DESACTIVADO.',
    save: 'Guardar',
    back: 'Atrás'
}
