import englishSettings from '../en/settings'

export default {
    ...englishSettings,
    survey: 'Estudio',
    app: 'Aplicación',
    other: 'Otro',
    surveyOverview: 'Resumen del estudio',
    referenceCells: 'Celdas de referencia',
    potentials: 'Potenciales',
    exportSurvey: 'Exportar estudio',
    about: 'Acerca de',
    language: 'Idioma',
    languageDescription: 'Seleccione el idioma utilizado por la aplicación',
    digitalMultimeter: 'Multímetro digital',
    externalLinks: 'Etiquetas QR y NFC',
    calculator: 'Calculadora de corrosión',
    defaultNames: 'Nombres predeterminados',
    defaultNamesDescription: 'Administre los nombres predeterminados para nuevos puntos de prueba, rectificadores y lecturas.',
    exportedFiles: 'Archivos exportados',
    exitWithoutSaving: 'Salir sin guardar',
    surveyOverviewDescription: 'Consulte las estadísticas generales del estudio y su estado de finalización',
    referenceCellsDescription: 'Añadir y eliminar celdas de referencia portátiles',
    potentialsDescription: 'Controlar las unidades predeterminadas y los tipos de lecturas de potencial',
    imagesDescription: 'Ver todas las imágenes asignadas a puntos de prueba y rectificadores de este estudio',
    exportSurveyDescription: 'Exportar datos del estudio a una hoja de cálculo y guardarla en el dispositivo',
    aboutDescription: 'Consultar la versión de la aplicación, la información legal y el contacto de soporte',
    multimeterDescription: 'Controlar la configuración del multímetro Bluetooth',
    externalLinksAndroidDescription: 'Ver las etiquetas escaneadas recientemente',
    externalLinksDescription: 'Iniciar el escaneo NFC y ver las etiquetas escaneadas recientemente',
    calculatorDescription: 'Ejecutar cálculos de protección catódica y exportar los resultados como archivos',
    exportedFilesDescription: 'Ver archivos de estudio exportados, eliminarlos o compartirlos con otras aplicaciones',
    exitDescription: 'Salir a la pantalla principal. Los cambios posteriores a la última sincronización no se guardarán. Use esta opción con cuidado.',
    privacyPolicy: 'Política de privacidad',
    terms: 'Términos y condiciones',
    licenses: 'Licencias',
    documentation: 'Documentación',
    support: 'Soporte',
    createdBy: 'Creado por',
    followOnX: 'Seguir en X',
    appVersion: 'Corpad para {{platform}}.\nVersión {{version}}',
    subscription: 'Suscripción',
    manage: 'Administrar',
    expiresOn: '(Caduca el {{date}})',
    check: 'Comprobar',
    upgrade: 'Actualizar',
    noLabels: 'No se encontraron etiquetas.',
    readNfc: 'Leer etiqueta NFC',
    recentlyScanned: 'Etiquetas escaneadas recientemente',
    scannedOn: 'Escaneada el {{date}}',
    noImages: 'No se encontraron imágenes.',
    loading: 'Cargando...',
    added: 'Añadida',
    surveyName: 'Nombre del estudio',
    numberOfImages: 'Número de imágenes',
    sizeOnDisk: 'Tamaño en disco',
    save: 'Guardar',
    category: 'Categoría',
    defaultNamePrefix: 'Prefijo de nombre predeterminado',
    defaultNamesHint: 'Los nombres predeterminados se usan al crear un elemento del estudio, como un punto de prueba, rectificador o tubería, o una nueva lectura. Puede declarar nombres manualmente en la pantalla de edición o personalizarlos aquí para usarlos automáticamente.',
    usePipelineName: 'Usar el nombre de la tubería como nombre predeterminado para derivaciones y elevadores de tubería',
    example: 'Ejemplo',
    error: 'Error',
    portableReferenceCells: 'Celdas de referencia portátiles',
    referenceCellsHint: 'Puede tener más de una celda de referencia portátil en un estudio. Las lecturas de potencial asignadas a la celda activa se mostrarán en la lista principal. Los potenciales creados automáticamente se asignan a la celda activa.',
    name: 'Nombre',
    selectType: 'Seleccionar tipo',
    referenceCellType: 'Tipo de celda de referencia',
    addReferenceCell: 'Añadir celda de referencia',
    standardPotentialTypes: 'Tipos de potencial estándar',
    customPotentialTypes: 'Tipos de potencial personalizados',
    addPotentialType: 'Añadir tipo de potencial',
    autoCreatePotentials: 'Crear potenciales automáticamente',
    autoCreateDescription: 'Las nuevas lecturas incluirán campos de potencial ACTIVADO/DESACTIVADO al crearse',
    newPotentialType: 'Nuevo tipo de potencial',
    potentialType: 'Tipo de potencial',
    create: 'Crear',
    mainReference: 'Referencia principal',
    unknownType: 'Tipo desconocido',
    lastUpdated: 'Última actualización',
    surveyArea: 'Área del estudio',
    radius: 'Radio',
    totalReadings: 'Número total de lecturas',
    images: 'Imágenes',
    imageAssets: 'Número de recursos de imagen',
    newSurvey: 'Mi estudio',
    testPoints: 'Puntos de prueba',
    rectifiers: 'Rectificadores',
    itemProperties: 'PROPIEDADES DE LOS ELEMENTOS',
    exportedItems: 'ELEMENTOS EXPORTADOS',
    format: 'FORMATO',
    mapLayers: 'CAPAS DEL MAPA',
    includeMapLayers: 'Incluir capas del mapa',
    includeImages: 'Incluir imágenes',
    yes: 'Sí',
    no: 'No',
    sorting: 'Orden',
    properties: 'Propiedades:',
    potentialsTitle: 'POTENCIALES',
    referenceCell: 'Celda de referencia:',
    potentialTypes: 'Tipos de potencial:',
    readingTypes: 'Tipos de lectura:',
    groupedBy: 'Agrupado por:',
    pipelines: 'Tuberías:',
    otherTitle: 'OTROS',
    exportProperties: 'Propiedades: ',
    export: 'Exportar',
    next: 'Siguiente',
    referenceCellTitle: 'CELDA DE REFERENCIA',
    potentialTypesTitle: 'TIPOS DE POTENCIAL',
    readingTypesTitle: 'TIPOS DE LECTURA',
    potentialGroupingTitle: 'AGRUPACIÓN DE POTENCIALES',
    exportPotentials: 'Exportar potenciales',
    groupReadingType: 'Agrupar por tipo de lectura',
    groupPipeline: 'Agrupar por tubería',
    unassigned: 'Sin asignar',
    preview: 'Vista previa',
    share: 'Compartir',
    openIn: 'Abrir en...',
    saveToDownloads: 'Guardar en Descargas',
    delete: 'Eliminar',
    noFiles: 'No se encontraron archivos',
    noFilesDescription: 'Aquí puede administrar archivos .csv, .kml y .zip después de exportar datos de estudios.',
    saved: 'Guardado',
    savedToDownloads: 'Guardado en Descargas',
    deleted: 'Se eliminó {{name}}',
    allFilesDeleted: 'Se eliminaron todos los archivos',
    deleteAll: 'Eliminar todo',
    exitingSurvey: 'Saliendo del estudio',
    exit: 'Salir',
    cancel: 'Cancelar',
    exporting: 'Exportando',
    creatingFile: 'Creando un archivo .{{type}} nuevo',
    includeImagesExport: 'Exportar imágenes',
    thirdPartyNotices: 'Avisos de terceros',
    licenseDescription: 'Los siguientes componentes se distribuyen bajo la licencia {{title}} que se reproduce a continuación:',
    licenseListDescription: 'La siguiente lista contiene software de terceros que puede estar incluido en parte de esta aplicación:',
    pipeline: 'Tubería',
    readingType: 'Tipo de lectura'
}
