import englishView from '../en/view'

export default {
    ...englishView,
    back: 'Atrás',
    testPoints: 'Puntos de prueba: {{count}}',
    noItems: 'No hay elementos',
    error: 'Error',
    resistance: 'Resistencia',
    resistivity: 'Resistividad',
    share: 'Compartir',
    save: 'Guardar',
    addingImage: 'Añadiendo imagen',
    savedToDownloads: 'Guardado en Descargas',
    deletingPhoto: 'Eliminando foto',
    showOnMap: 'Mostrar en el mapa',
    addPhoto: 'Añadir una foto',
    addReading: 'Añadir lectura',
    imagesCount: 'Imágenes ({{count}}/6)',
    edit: 'Editar',
    createLabel: 'Crear etiqueta',
    delete: 'Eliminar',
    cancel: 'Cancelar',
    show: 'Mostrar',
    hide: 'Ocultar',
    controls: 'controles',
    currentMeasurement: 'Medición de corriente',
    direct: 'Directa',
    shunt: 'Shunt',
    material: 'Material',
    anodeMaterial: 'Material del ánodo',
    anode: 'Ánodo',
    bedType: 'Tipo de lecho',
    enclosureType: 'Tipo de carcasa',
    anodeOutputCurrent: 'Corriente de salida del ánodo',
    connectedTo: 'Conectado a',
    disconnected: 'Desconectado',
    type: 'Tipo',
    area: 'Área',
    density: 'Densidad',
    current: 'Corriente',
    voltage: 'Tensión',
    target: 'Objetivo',
    maxValue: 'Máx. {{value}}',
    minValue: 'Mín. {{value}}',
    shuntRatio: 'Relación del shunt',
    factor: 'Factor',
    voltageDrop: 'Caída de tensión',
    isolationType: 'Tipo de aislamiento',
    shorted: 'Cortocircuitado',
    diameter: 'Diámetro',
    pipeline: 'Tubería',
    comment: 'Comentario',
    description: 'Descripción',
    status: 'Estado',
    isolated: 'Aislado',
    maxVoltage: 'Tensión máx.',
    maxCurrent: 'Corriente máx.',
    model: 'Modelo',
    serialNumber: 'Número de serie',
    powerSource: 'Fuente de alimentación',
    currentControl: 'Control de corriente',
    size: 'Tamaño',
    coating: 'Revestimiento',
    product: 'Producto',
    average: 'Promedio',
    layers: 'Capas',
    layer: 'Capa ({{start}} - {{end}} {{unit}})',
    bytes: 'bytes',
    nfc: {
        preparing: 'Creando enlace...',
        ready: 'Listo para escribir',
        writing: 'Escribiendo...',
        success: 'Completado',
        error: 'Error',
        holdPhone: 'Acerque el teléfono a la etiqueta NFC para registrar los datos del elemento.',
        written: 'La información del elemento se escribió en la etiqueta NFC.',
        notFormatted: 'La etiqueta NFC no está formateada. Más información en',
        readOnly: 'La etiqueta NFC está bloqueada en modo de solo lectura.',
        notEnoughSpace: 'No hay suficiente espacio en la etiqueta NFC. Más información en',
        turnedOff: 'NFC está desactivado. Actívelo en la configuración.',
        notSupported: 'NFC no es compatible con este dispositivo.',
        linkTooLong: 'Se registró demasiada información en la etiqueta NFC.',
        cancel: 'Cancelar',
        close: 'Cerrar',
        retry: 'Reintentar'
    }
}
